### PR TITLE
Activate Ruby environment using version managers

### LINKED ISSUE #21: Can't launch debugger for Rails project with Rbenv.
I'm running Rails project:
- Rails 6.1.4
- Ruby 3.0.3
with Ruby version managed by Rbenv.
I have `gem 'debug'` listed in my project's Gemfile, and binstubs generated to `./bin/rdbg`.
Gems are bundled with Bundler `2.2.32`

Here is the "launch" config I'm trying to use 
```
{
  "name": "Debug Rails server",
  "type": "rdbg",
  "request": "launch",
  "useBundler": false,
  "script": "server",
  "rdbgPath": "${workspaceFolder}/bin/rdbg",
  "command": "${workspaceFolder}/bin/rails",
  "cwd":"${workspaceFolder}"
}
```

I've changed `command` from default to `"${workspaceFolder}/bin/rails"` to bypass logic, described [here](https://github.com/ruby/vscode-rdbg/blob/master/src/extension.ts#L363).
I'm using `zsh` as my shell.
So the problem I've  faced is that function `get_sock_path` generates the next command to shell: `"/bin/zsh -l -c '${workspaceFolder}/bin/rdbg --util=gen-sockpath'"` (`${workspaceFolder}` here and further the absolute path to my project) . And this command, when executed, does not follow `rbenv`'s  shims and thows the error 
```
Activating bundler (2.2.32) failed:
Could not find 'bundler' (2.2.32) required by your ${workspaceFolder}/Gemfile.lock.
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.2.32`
```
This is because `make_shell_command` returns a command (`/bin/zsh -l -c '...'`) that is when executing is not caught by `rbenv` Even If I add `cd ${workspaceFolder}` it won't work:
```
$ /bin/zsh -l -c 'cd ${workspaceFolder} && which ruby'
/usr/bin/ruby
$ /bin/zsh -l -c 'cd ${workspaceFolder} && ruby --version'
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
$ git clone git@github.com:ruby/vscode-rdbg.git
$ /bin/zsh -l -c 'cd ${workspaceFolder} && which ruby'
/usr/bin/ruby
$ /bin/zsh -l -c 'cd ${workspaceFolder} && ruby --version'
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]


$ cd ${workspaceFolder} && which ruby
$HOME/.rbenv/shims/ruby
$ cd ${workspaceFolder} && ruby --version
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-darwin20]
```

I haven't had a chance to debug the extension deeply enough and do not clear to me why is this necessary to use that "sequence", but this causes problems.
Is there any way for code to be changed in order to work properly with such widely used Ruby environment management as `rbenv`?

### PR DESCRIPTION
**Pull request by vinistock**
Closes #21

Add Ruby environment activation through version managers. This PR
- Exposes a new configuration to select a version manager
- Implements how to activate the Ruby environment based on each manager
- Starts activating the environment before trying to run the `rdbg` executable

### CODE REVIEW

**Comment by ko1** [comment]
Sorry I forget to response on it.

(1) do you plan to make a npm package for it?
(2) For "none" I think it is enough to use `injectRubyEnvironment` without `rbenv`, ... is enough (and remove all other shell dependent code), at least on rbenv. What do you think about it? In other words, I don't want to ask setting `rdbg.rubyVersionManager` if not needed.

**Comment by ko1** [comment]
Another question.

On rbenv, `RBENV_VERSION` is specified at first setting. if `.ruby-version` is rewritten, it seems it doesn't applied for VSCode without restarting the VSCode process. Is it intentional? I'm not sure how often such a case happened.

**Comment by vinistock** [comment]
I've rebased the PR and modified the changes in #124, since we want all shells to use interactive mode to load `rbenv`, `chruby` or any other manager.

Concerning your questions
1. Yes, we hope to turn the activation into a package so that we don't have to keep duplicating code between the Ruby LSP, RDBG and any other extension that wants to launch Ruby
2. I'm not sure I understand this one. When the version manager is `none` (which is the default), we don't invoke `injectRubyEnvironment`
3. If you want to re-activate the Ruby environment and inject the variables into the node process when `.ruby-version` changes, then we have to use a VS Code file watcher to track changes to the file and then trigger re-activation if any modifications happen

**Comment by ko1** [comment]
Thank you for your quick reply.

> Yes, we hope to turn the activation into a package so that we don't have to keep duplicating code between the Ruby LSP, RDBG and any other extension that wants to launch Ruby

If it will be released soon, I want to wait for it.

> I'm not sure I understand this one. When the version manager is none (which is the default), we don't invoke injectRubyEnvironment

Yes. My idea is "assuming users use `rbenv` and `injectRubyEnvironment` for `none` will setup `rbenv` environment variables and no need to call shell for the following commands. But it has an issue for (3).

> If you want to re-activate the Ruby environment and inject the variables into the node process when .ruby-version changes, then we have to use a VS Code file watcher to track changes to the file and then trigger re-activation if any modifications happen

I understand the technique. My question was it is intentional or not for `.ruby-version` changes. As I wrote " I'm not sure how often such a case happened." so if the real case is not many, I agree we can ignore it.

File: src/extension.ts [hunk 1]
```diff
@@ -272,20 +294,68 @@ class RdbgAdapterDescriptorFactory implements DebugAdapterDescriptorFactory {
...
-				// Thus, we need to run this command as the interactive shell.
-				// FYI: https://zsh.sourceforge.io/Guide/zshguide02.html
-				return shell + " -l -c -i '" + cmd + "'";
-			default:
-				return cmd;
+
+		if (this.support_login(shell)) {
+			return shell + " -lic '" + cmd + "'";
+		} else {
+			return cmd;
```
Comment (ono-max) [inline src/extension.ts:301]: Can you cut out this part to another PR? I can merge this part soon.

Comment (vinistock) [reply src/extension.ts:301]: Why not merge this PR instead?

Comment (ono-max) [reply src/extension.ts:301]: Sorry, I can't merge this PR since @ko1-san is reviewing this PR, and he decides it. And the reason why I ask you to cut this part to another PR is that it is significant to merge this part regardless of this feature.

Comment (ono-max) [reply src/extension.ts:301]: But, it's just a suggestion, I'll leave it up to you.

Comment (vinistock) [reply src/extension.ts:301]: I understand your point of view, but my sincere opinion is that we should focus on getting this PR merged.

Using Ruby version managers is common practice on the community and making sure the environment is activated properly is essential to get all of the benefits of RDBG in the editor.

**Comment by ko1** [comment]
I think no configuration is better but I feel current proposed documentation asks user to write it if they uses a version manager. So I want to rewrite it after merge.
@vinistock could you allow me to modify then after merging?

**Comment by vinistock** [comment]
Can you clarify what you mean by `no configuration`? Do you mean trying to guess which version manager the developer uses?

Totally okay with you refactoring as needed. Just trying to understand your perspective since the long term vision is for the Ruby LSP and RDBG to both use an NPM package for Ruby environment activation.

**Comment by vinistock** [comment]
We're adding the `auto` option as the [default for the Ruby LSP](https://github.com/Shopify/vscode-ruby-lsp/pull/437), which automatically detects the user's version manager. Would that what you're thinking about?

**Comment by ko1** [comment]
@vinistock 
Sorry for the late response but it seems conflicting.
Could you rebase it or can I make a patch?

**Comment by firien** [comment]
`promisify` was removed with #41. I have nothing against `promisify` - it was really the embedded `require` that caught my eye and provided impetus for e1040ba.
For consistency, either this should adopt the Promise wrapped callback style, or #41 should revert to `promisify` version. As noted in #41 - there are also event based versions of `child_process.exec` in here - so this would introduce yet another flavor of `child_process.exec`

**Comment by ono-max** [comment]
Thanks @firien san.

I'm ok with using `promisify`, so let's use `promisify` in https://github.com/ruby/vscode-rdbg/pull/41, in another PR.
